/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NodeSelectionOptions {
  macOS?: NodeSelectionOptionsMacOs
}
export interface NodeSelectionOptionsMacOs {
  shouldManuallyEnableAccessibility: (bundleIdentifier: string) => boolean
}
export class NodeSelection {
  checkAccessibilityPermissions(): boolean
  constructor(options?: NodeSelectionOptions | undefined | null)
}
