/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NodeSelectionOptions {
  macOS?: NodeSelectionOptionsMacOs
}
export interface NodeSelectionOptionsMacOs {
  shouldManuallyEnableAccessibility: (bundleIdentifier: string) => boolean
}
export interface CheckAccessibilityPermissionOptions {
  prompt: boolean
}
export class NodeSelection {
  constructor(options?: NodeSelectionOptions | undefined | null)
  checkAccessibilityPermissions(options?: CheckAccessibilityPermissionOptions | undefined | null): Promise<unknown>
  getSelection(): Promise<unknown>
}
